### PR TITLE
upgrade elasticsearch

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/27)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Fixed - can look into using resource-filtering in future so it happens automatically

**Comment by vvanholl** [comment]
Thanks !

**Comment by davidkarlsen** [comment]
@vvanholl Could you do a release of it as well - so I can upgrade my image: https://hub.docker.com/r/davidkarlsen/elasticsearchhq/

**Comment by vvanholl** [comment]
I should do the release today or tomorrow since I am implementing new features like per index metrics.

**Comment by davidkarlsen** [comment]
Do you have an updated dashboard at grafana.net for the new index features? https://grafana.com/dashboards/266

**Pull request merged**
