### PR TITLE
support ES 5.5.1

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/48)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@vvanholl

**Comment by davidkarlsen** [comment]
ping?

**Comment by vvanholl** [comment]
Thank you :) sorry for waiting, but I am currently working on other projects

**Comment by davidkarlsen** [comment]
Great - thanks - sorry for pinging so much - I don't know what is your preferred way to receive a heads up (so that I know it's been seen) :)

**Comment by vvanholl** [comment]
Hi @davidkarlsen , I am currently working on my next CI/CD environment allowing soon better and faster integration.

**Pull request merged**
