### PR TITLE
Support ES 5.4.2

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/44)

### CODE REVIEW

**Comment by vvanholl** [comment]
Thank you ! :)

**Comment by davidkarlsen** [comment]
@vvanholl could you please do a release too?

**Comment by vvanholl** [comment]
Hello @davidkarlsen, I plan a release today, the time to fix some bugs and bring improvements

**Comment by davidkarlsen** [comment]
Great - thanks - looking forward to upgrade - have a nice weekend!

**Pull request merged**
