### PR TITLE
Upgrade to ES 7.10.0 and release version 7.10.0

### PR DESCRIPTION
**Pull request by vvanholl**

### CODE REVIEW

**Comment by vvanholl** [comment]
This is a Work In Progress : There are many problems to be solved

**Comment by vvanholl** [comment]
Solved : https://github.com/elastic/elasticsearch/commit/7bb748da8c1b0579595b017d3789294a74fb59eb#diff-7b6fc64bd4764caeacef1c21fcbca9d7b868d2d42ab936a5c1f0d91363f646d2

**Comment by vvanholl** [comment]
Solved : https://github.com/elastic/elasticsearch/commit/dd74be0f839e963eac14354ef5cfe2c8cb264fb6#diff-7f086ade4fd871faac709dd4661f721187044b112111dd27ff588e6ed5d0f15d

**Comment by vvanholl** [comment]
This should now work but a review would be appreciated. @davidkarlsen

**Comment by davidkarlsen** [comment]
LGTM.
I've moved to using containers for exporting metrics so that I'm not using this plugin any longer and avoid having to bake images - so I haven't run it - but the changes look sane.

**Pull request merged**
