### PR TITLE
Upgrade to Elasticsearch 6.7.1

### PR DESCRIPTION
**Pull request by vvanholl**

### CODE REVIEW

**Comment by vvanholl** [comment]
Note that the build fails because it requires Java 12.

I currently use the official Gradle Docker image for Java 11 (5.3.1-jdk11) and for the moment there's no new image that supports Java 12 as you can see here : 

https://github.com/keeganwitt/docker-gradle/issues/91

**Comment by vvanholl** [comment]
I will retry with my own Docker image built this evening : compuscene/gradle:5.3.1-jdk12

**Comment by davidkarlsen** [comment]
https://github.com/keeganwitt/docker-gradle/pull/92

**Comment by vvanholl** [comment]
This is now OK with my temporary custom JDK12/Gradle 5.3 Docker image

**Pull request merged**
