### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by kbecic**
Prepare release of 7.2.0.0 related to #198 #199

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@vvanholl Let's cut a new release.

**Comment by vvanholl** [comment]
@lukas-vlcek @kbecic Before releasing we have to pass integration tests which are still failing
As you can see there https://gitlab.com/vvanholl/elasticsearch-prometheus-exporter/-/jobs/250803894

As a prerequisite I had to upgrade the Gradle version.

Vincent

**Comment by vvanholl** [comment]
After few investigations it seems Elasticsearch doesn't want to run as root user :
```
[2019-07-12T19:33:59,743][ERROR][o.e.b.Bootstrap          ] [node-1] Exception
java.lang.RuntimeException: can not run elasticsearch as root
```

I am working to find a workaround

**Comment by lukas-vlcek** [comment]
Hmmm... before I merged https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/199 I made sure it passed tests on my machine (but yea, I had to upgrade Gradle first). However, I did not get any error wrt to root user obviously.
It is shame CI does not run tests when PR is made from external repos.

**Comment by vvanholl** [comment]
I don't know why by upgrading Gradle docker image version 5.3.1 to 5.4.1 the default user changed from "gradle" to "root".

**Comment by vvanholl** [comment]
Not the best workaround of my life but it works :
```su gradle -c 'gradle build'```

We are ready to release : https://gitlab.com/vvanholl/elasticsearch-prometheus-exporter/-/jobs/250831860

**Comment by kbecic** [comment]
I was running local ITs with latest gradle so i didn't notice any issues. Can you release now? Do you need anything else from my side?

**Comment by lukas-vlcek** [comment]
@kbecic May be the last nit, do you think you can update the commit message to call out specific release version? So instead generic "Prepare release" it will read "Release 7.2.0" for example. It is a lot more useful when one list commits like `git log --online`.
Otherwise LGTM.

**Comment by lukas-vlcek** [comment]
@vvanholl Just an idea but consider using CI that supports testing PR from external repos. Right now the CI is run only when the PR is created from branch in this repo. This is IMO not supporting community well.

**Comment by kbecic** [comment]
@lukas-vlcek @vvanholl changed commit message. It should be ready for merge now.

**Comment by Nilubkal** [comment]
do you foresee a release soon guys ?

**Comment by vvanholl** [comment]
@lukas-vlcek Maybe should I consider to switch to GitHub Actions

**Comment by lukas-vlcek** [comment]
@vvanholl I am not familiar with GitHub Actions but if it makes sense then go for it.

**Pull request merged**
