### PR TITLE
support es 6

### PR DESCRIPTION
**Pull request by davidkarlsen**
Not verified in any way - let's see if build passes

---
This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/69)

### CODE REVIEW

**Comment by vvanholl** [comment]
@davidkarlsen I'am sad to say build failed : https://gist.github.com/vvanholl/ed14299072e8cccfd59a4b0bc6821f57

**Comment by davidkarlsen** [comment]
Ah, those got removed: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking_60_stats_changes.html

**Comment by vvanholl** [comment]
Another change is in RestPrometheusMetricsAction, where BaseRestHandler is abstract  and you need to implement getName method : 
```
    @Override
    public String getName() {
        return "prometheus_metrics_action";
    }
```

**Comment by vvanholl** [comment]
Another thing, I created a dedicated 6.x branch and changed PR to go on it.
It's to avoid changes on master branch which is for stable version

**Comment by mikn** [comment]
Oh. I thought that 6.0 is the stable version now? I'm just about to stand up an ES cluster and am eagerly awaiting this plugin to update to 6.0 so that I'm able to get stats. Out of the ones I've tried, this is the one that has had far best coverage. :)
(Also thank you both for some solid good work!)

**Comment by vvanholl** [comment]
@mikn : my bad, I didn't noticed ES 6.0.0 was officially released ! :)

**Comment by piotrkochan** [comment]
When this will be available to use? 

https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-6.0.0.zip

> The specified key does not exist.

**Pull request merged**
