### PR TITLE
Fix junit report path

### PR DESCRIPTION
**Pull request by lukas-vlcek**

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Trying to get myself more familiar with Gitlab CI. IMO the report path needs to point to different folder.
This should fix [the warning](https://gitlab.com/vvanholl/elasticsearch-prometheus-exporter/-/jobs/115528647):
```
BUILD SUCCESSFUL in 1m 57s
39 actionable tasks: 34 executed, 5 up-to-date
Not uploading cache master-1 due to policy
Uploading artifacts...
WARNING: build/test-results/test/TEST-*.xml: no matching files 
ERROR: No files to upload                          
Job succeeded
```

**Comment by vvanholl** [comment]
I added you as collaborator on my project, could you instead create a branch on it and push ?
Normally GitLab CI could run in this case.

**Comment by lukas-vlcek** [comment]
[Looking much better](https://gitlab.com/vvanholl/elasticsearch-prometheus-exporter/-/jobs/116049703) now:
```
> Task :integTestRunner
==> Test Info: seed=3466474F9E2A9EC1; jvm=1; suite=1
==> Test Summary: 1 suite, 20 tests

> Task :integTestCluster#node1.stop
> Task :integTestCluster#node0.stop
> Task :integTest
> Task :check

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 0s
39 actionable tasks: 34 executed, 5 up-to-date
Not uploading cache fix_test_report_path-2 due to policy
Uploading artifacts...
build/reports/integTestRunnerJunit/TEST-*.xml: found 1 matching files 
Uploading artifacts to coordinator... ok            id=116049703 responseStatus=201 Created token=jg8-zxf8
Job succeeded
```

**Comment by lukas-vlcek** [comment]
Interesting, when I created `fix_test_report_path` in upstream (i.e. this repo) then Gitlab CI started pipeline for my original PR (i.e. from `lukas-vlcek` repo). Anyway, next time I will create branch in this upstream repo only. This seems to be the way we have to go atm.

**Pull request merged**
