### PR TITLE
ES 5.6.3

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/61)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@vvanholl

**Comment by vvanholl** [comment]
Hi @davidkarlsen , There's a conflict while merging with README file. Can you fix it ?

**Comment by davidkarlsen** [comment]
@vvanholl fixed

**Comment by vvanholl** [comment]
Thanks :)

**Pull request merged**
