### PR TITLE
release for es 6.3.0

### PR DESCRIPTION
**Pull request by davidkarlsen**
@vvanholl 

This change is [Reviewable](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/106)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@vvanholl ping?

**Comment by wfindley** [comment]
careful.  They now require plugins to not have /elasticsearch in the zip file.

**Comment by wfindley** [comment]
I built this, but had to repackage the zip so that `/elasticsearch/foo.jar` became `/foo.jar`

**Comment by wfindley** [comment]
https://github.com/elastic/elasticsearch/pull/28589

**Pull request merged**
