### PR TITLE
Upgrade to ES 7.6.1 and release 7.6.1.0

### PR DESCRIPTION
**Pull request by foxdalas**

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@foxdalas Did you run `gradle clean check`? Do all tests pass for you without issues?
I am running into some issues but they may be related to changes in upstream ES integ-test part... I am investigating.

```
> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.2.2
  OS Info               : Mac OS X 10.14.6 (x86_64)
  JDK Version           : 13 (Oracle Corporation 13.0.2 [OpenJDK 64-Bit Server VM 13.0.2+8])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
  Random Testing Seed   : EE896A7ACFFA25FA
  In FIPS 140 mode      : false
=======================================

> Task :integTestRunner

REPRODUCE WITH: ./gradlew ':integTestRunner' --tests "org.elasticsearch.rest.PrometheusRestHandlerClientYamlTestSuiteIT" -Dtests.method="test {yaml=snapshot.get/10_basic/Get snapshot info with metadata}" -Dtests.seed=EE896A7ACFFA25FA -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=Europe/Luxembourg -Dcompiler.java=13

org.elasticsearch.rest.PrometheusRestHandlerClientYamlTestSuiteIT > test {yaml=snapshot.get/10_basic/Get snapshot info with metadata} FAILED
    java.lang.AssertionError: Failure at [snapshot.get/10_basic:4]: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[test_repo_get_1] [[cM57etDrSqyyaun1PchGdg, 'RemoteTransportException[[integTest-0][127.0.0.1:59291][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[test_repo_get_1] a file written by master to the store [/Users/lvlcek/projects/elasticsearch-prometheus-exporter/build/testclusters/integTest-0/repo/test_repo_get_1_loc] cannot be accessed on the node [{integTest-0}{cM57etDrSqyyaun1PchGdg}{ZMn_-CCPTQiQ6daMgtWNnQ}{127.0.0.1}{127.0.0.1:59291}{dim}{testattr=test}]. This might indicate that the store [/Users/lvlcek/projects/elasticsearch-prometheus-exporter/build/testclusters/integTest-0/repo/test_repo_get_1_loc] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]; nested: NoSuchFileException[/Users/lvlcek/projects/elasticsearch-prometheus-exporter/build/testclusters/integTest-0/repo/test_repo_get_1_loc/tests-yrV1IW-KTXOMNoMfzRb11Q/master.dat];']]",
    [...]
```

**Comment by olgakorichkovskaya** [comment]
Can I help to speed up this PR?

**Comment by foxdalas** [comment]
@olgakorichkovskaya yes sure

**Comment by lukas-vlcek** [comment]
What I would look at are Elasticsearch tests that use more nodes. They setup `path.repo` setting and also explicitly create that file. This might be something we should do as well. One example is here:
https://github.com/elastic/elasticsearch/blob/984670b34d34fa0608fc00da6d941d3aaa41f5a7/qa/smoke-test-multinode/build.gradle

**Pull request closed without merging**
