### PR TITLE
Upgrade to ES 7.3.0 and Release version 7.3.0.0

### PR DESCRIPTION
**Pull request by vvanholl**

### CODE REVIEW

**Comment by vvanholl** [comment]
The role of this PR is to release version 7.3.0.0 in order to unlock releasing next versions

**Comment by vvanholl** [comment]
Even if there are things to fix or improve

**Comment by lukas-vlcek** [comment]
Once this is merged we should close the following PRs: https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/210, https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/206, https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/218, https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/219

**Comment by vvanholl** [comment]
Thanks a lot @lukas-vlcek !

**Pull request merged**
