### PR TITLE
Create version for Elasticsearch 7.16.2

### PR DESCRIPTION
**Pull request by dhpowrhost**

### CODE REVIEW

**Comment by henrist** [comment]
Should probably also update the `Install` header in README to point to 7.16.2.0

**Comment by jeroenhartgers** [comment]
I would highly appreciate a release for this plugin. It is keeping me from releasing my own customised Elasticsearch container.

**Review by jeroenhartgers — DISMISSED** [review]

**Comment by dhpowrhost** [comment]
> I would highly appreciate a release for this plugin. It is keeping me from releasing my own customised Elasticsearch container.

Yes done

**Comment by jeroenhartgers** [comment]
> > I would highly appreciate a release for this plugin. It is keeping me from releasing my own customised Elasticsearch container.
> 
> Yes done

I will use your fork. Thanks a bunch!

**Comment by djsly** [comment]
Also waiting on this to update to 7.16.2 for the log4j issue

**Comment by djsly** [comment]
Ready to be merged ?  Side question can me makes this exporter not patch dependant ? I 'm not sure ensuring the exact same version is required for patch update..

**Comment by dhpowrhost** [comment]
> Ready to be merged ? Side question can me makes this exporter not patch dependant ? I 'm not sure ensuring the exact same version is required for patch update..

Yeah that would be appreciated.

**Review by vvanholl — APPROVED** [review]
LGTM

**Pull request merged**
