### PR TITLE
Upgrade to ES 7.7.1 and release version 7.7.1.0

### LINKED ISSUE #272: Release for ES 7.7.1
Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/7.7/release-notes-7.7.1.html

### PR DESCRIPTION
**Pull request by martbhell**
Hello!

Fixes #272 

I just copied a previous PR #269  - wondering if the integration tests pass without any more changes

### CODE REVIEW

**Comment by lwille** [comment]
can we get this tested and merged?

**Comment by martbhell** [comment]
Looks like https://gitlab.com/vvanholl/elasticsearch-prometheus-exporter/commits/master doesn't run any pipelines so I guess testing here is manual.

**Comment by lukas-vlcek** [comment]
Unfortunately, atm the automatic branch PR testing does not kicks in if thee PR is not based on branch in this repo. As mentioned in https://github.com/vvanholl/elasticsearch-prometheus-exporter#testing you can just do
```
gradle clean check
```
to see if tests will pass.

**Comment by martbhell** [comment]
Aha. Thanks and sorry for that. 

I can see in a week or two after a short holiday if I can try out gradle :)

**Comment by vvanholl** [comment]
Hi @martbhell, Thank you for your PR. I am starting reviewing it on my side.

**Comment by vvanholl** [comment]
There are some slightly changes to do. I have created a branch with a working commit on my side : https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/13273d2c99980505964139f5f1f41063d39256c9
You can take the changes in your PR.

**Comment by martbhell** [comment]
> There are some slightly changes to do. I have created a branch with a working commit on my side : [13273d2](https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/13273d2c99980505964139f5f1f41063d39256c9)
> You can take the changes in your PR.

Cool! If you want to either push into my fork or just use your own branch in a new PR and close this. I am without a computer for a week now :)

**Pull request merged**
